spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:db_resource}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:superman}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
config:
  aws:
    region: us-east-1
    s3:
      url: http://127.0.0.1:4566
      access-key: localstack
      secret-key: localstack
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_ENDPOINTS:localhost:9092,localhost:9093,localhost:9094}
  topic:
    resources: resources
    partitions.count: 3
    replication.factor: 3
